{% set name = "tesseract" %}
{% set version = "4.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/tesseract-ocr/{{ name }}/archive/{{ version }}.tar.gz
    sha256: 2a66ff0d8595bff8f04032165e6c936389b1e5727c3ce5a27b3e059d218db1cb
    folder: tesseract
    patches:
      - 0001_update_CMakeLists_txt.patch
  - url: https://github.com/tesseract-ocr/tessdata_fast/archive/4.0.0.tar.gz
    sha256: f1b71e97f27bafffb6a730ee66fd9dc021afc38f318fdc80a464a84a519227fe
    folder: tessdata_fast
    

build:
  number: 5
  skip: True  # [not win or vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf  # [not win]
    - automake  # [not win]
    - leptonica    
    - libtool  # [not win]
    - libtiff
    - pkg-config  # [not win]
    - make  # [not win]
    - cmake  # [win]
    - curl <7.71.1  # [win]
    - m2-unzip  # [win]    

  host:
    - giflib  # [not win]
    - libarchive
    - jpeg
    - leptonica
    - libpng
    - libtiff
    - libwebp
    - openjpeg
    - xz  # [not win]
    - zlib

  run:
    - libpng
    - jpeg
    - libtiff
    - zlib
    - leptonica
    - libwebp
    - libarchive
    - xz  # [not win]
    - openjpeg
    - giflib  # [not win]


test:
  files:
    - eurotext.tif
  commands:
    - tesseract --help
    - tesseract --list-langs
    - tesseract eurotext.tif outputbase

about:
  home: https://github.com/tesseract-ocr/tesseract
  license: Apache-2.0
  license_family: Apache
  license_file: tesseract/LICENSE
  summary: 'An optical character recognition (OCR) engine'

  description: |
    Tesseract is an OCR engine with support for unicode and the ability
    to recognize more than 100 languages out of the box. It can be
    trained to recognize other languages.
  doc_url: https://github.com/tesseract-ocr/tesseract
  dev_url: https://github.com/tesseract-ocr/tesseract

extra:
  recipe-maintainers:
    - CurtLH
    - carlodri
    - adbeda
    - oblute
    - xylar
    
