{% set name = "tesseract" %}
{% set version = "4.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/tesseract-ocr/{{ name }}/archive/{{ version }}.tar.gz
    sha256: 83dc56b544be938983f528c777e4e1d906205b0f6dc0110afc223f2cc1cec6d3
    folder: tesseract
    patches:
      - 0001_update_CMakeLists_txt.patch
  - url: https://github.com/tesseract-ocr/tessdata_fast/archive/4.1.0.tar.gz
    sha256: d0e3bb6f3b4e75748680524a1d116f2bfb145618f8ceed55b279d15098a530f9
    folder: tessdata_fast
    

build:
  number: 6
  skip: True  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool  # [not win]
    - pkg-config  # [not win]
    - make  # [not win]
    - cmake  # [win]

  host:
    - giflib  # [not win]
    - libarchive
    - jpeg
    - leptonica  # [not win]
    - leptonica  <1.80  # [win]
    - libpng
    - libtiff
    - libwebp
    - openjpeg
    - xz  # [not win]
    - zlib

  run:
    - libpng
    - jpeg
    - libtiff
    - zlib
    - leptonica
    - libwebp
    - libarchive
    - xz  # [not win]
    - openjpeg
    - giflib  # [not win]


test:
  files:
    - eurotext.tif
  commands:
    - tesseract --help
    - tesseract --list-langs
    - tesseract eurotext.tif outputbase

about:
  home: https://github.com/tesseract-ocr/tesseract
  license: Apache-2.0
  license_family: Apache
  license_file: tesseract/LICENSE
  summary: 'An optical character recognition (OCR) engine'

  description: |
    Tesseract is an OCR engine with support for unicode and the ability
    to recognize more than 100 languages out of the box. It can be
    trained to recognize other languages.
  doc_url: https://github.com/tesseract-ocr/tesseract
  dev_url: https://github.com/tesseract-ocr/tesseract

extra:
  recipe-maintainers:
    - mxr-conda
    - CurtLH
    - carlodri
    - adbeda
    - oblute
    - xylar
    - izahn
