{% set name = "tesseract" %}
{% set version = "4.0.0" %}
{% set sha256 = "5dcb37198336b6953843b461ee535df1401b41008d550fc9e43d0edabca7adb1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/tesseract-ocr/{{ name }}/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}
    folder: tesseract
  - url: https://github.com/tesseract-ocr/tessdata/archive/3.04.00.tar.gz
    sha256: 5dcb37198336b6953843b461ee535df1401b41008d550fc9e43d0edabca7adb1
    folder: tessdata

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - automake
    - autoconf
    - pkg-config
    - libtool
  host:
    - libpng
    - jpeg
    - libtiff
    - libtool
    - zlib
    - leptonica
    - libwebp
    - xz
    - openjpeg
    - giflib
  run:
    - libpng
    - jpeg
    - libtiff
    - zlib
    - leptonica
    - libwebp
    - xz
    - openjpeg
    - giflib

test:
  files:
    - image.png
  commands:
    - tesseract --help
    - tesseract --list-langs
    - tesseract image.png outputbase

about:
  home: https://github.com/tesseract-ocr/tesseract
  license: Apache-2.0
  license_family: Apache
  license_file: tesseract/LICENSE
  summary: 'An optical character recognition (OCR) engine'

  description: |
    Tesseract is an OCR engine with support for unicode and the ability
    to recognize more than 100 languages out of the box. It can be
    trained to recognize other languages.
  doc_url: https://github.com/tesseract-ocr/tesseract
  dev_url: https://github.com/tesseract-ocr/tesseract

extra:
  recipe-maintainers:
    - CurtLH
