appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: rUfduKkRg/Bv6bdloqqmTGT5KHgZyoFlJu/kmQjU4uTHAt4Sv3cOz8xsLG9JFB3tZXc0kvtTIQbjUJi3IiJT+Nt3tem9EdE7Cy49RpFCPSNI/ctCFEDytSwbp7rw95n+jcMHXj7UeojpV6vTRYjcBZJamFCJ7OQQOffy6y5ii2q4oFBi8qv+v5ClO1jreybpylFVliMyfFAwCxt5DkNbeCLvqF/NXvxq4kDQafZXK8+HCWzHHq2dQ1vyDyIJWb3LihZUAF+XyQGF9YhPVEDIrM0hbNIf38mSH1EeNplCH+VlTbHd15j5Zv29fjwCqOmWGFA4qIqe0L7d/vWdO3s6kRXaPG7p5R2EdeuuhmK+CoJBuOax/QwV/8F4pI9WZjOEMIAZRTU1ZLQr6SElnJeWXhjPmS2MKTYbiEYKsddTtjCNt2NK7//b00wHlxjPJejIBxi7okqAJa7YHNRWYBfivdMd/SE+l1ees2Sy62ufxORe+tuoWp7rYQ5bHrmBE//ovy/cuuQL9MrmLps2LlYwSJ45rS4ZwukuIRqFDIKs4hrTz98dBfEbMQ7sLD300ZTh+bS0G0rZ8aVpjVYzAF2CRasq/iq2nzDyQS3Zj7RYHJ25zWMlQ0MvNlMRi4bp/FPbgf1IPfCIcXT4zJLQEOzqSZqbX/98WKUKMOVgbdgw1bw=}
provider:
  win: azure
